CREATE TABLE IF NOT EXISTS CLIENTE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255),
    CPF VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS INSTITUICAO_FINANCEIRA (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CNPJ VARCHAR(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTO (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    PRECO_INICIAL DOUBLE NOT NULL,
    DTYPE VARCHAR(255),
    TIPO VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS LEILAO (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    DATA_INICIAL DATE,
    DATA_FINAL DATE,
    LOCAL VARCHAR(255),
    STATUS VARCHAR(255),
    DESCRICAO VARCHAR(255),
    HORARIO_INICIO TIME,
    HORARIO_FIM TIME
);

CREATE TABLE IF NOT EXISTS LANCE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CLIENTE_ID BIGINT,
    PRODUTO_ID BIGINT,
    VALOR DOUBLE,
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID),
    FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO(ID)
);

-- Tabelas de associação
CREATE TABLE IF NOT EXISTS LEILAO_PRODUTOS (
    LEILAO_ID BIGINT,
    PRODUTOS_ID BIGINT,
    FOREIGN KEY (LEILAO_ID) REFERENCES LEILAO(ID),
    FOREIGN KEY (PRODUTOS_ID) REFERENCES PRODUTO(ID)
);

CREATE TABLE IF NOT EXISTS LEILAO_CLIENTES (
    LEILAO_ID BIGINT,
    CLIENTES_ID BIGINT,
    FOREIGN KEY (LEILAO_ID) REFERENCES LEILAO(ID),
    FOREIGN KEY (CLIENTES_ID) REFERENCES CLIENTE(ID)
);

CREATE TABLE IF NOT EXISTS LEILAO_INSTITUICOES_FINANCEIRAS (
    LEILAO_ID BIGINT,
    INSTITUICOES_FINANCEIRAS_ID BIGINT,
    FOREIGN KEY (LEILAO_ID) REFERENCES LEILAO(ID),
    FOREIGN KEY (INSTITUICOES_FINANCEIRAS_ID) REFERENCES INSTITUICAO_FINANCEIRA(ID)
);

CREATE TABLE IF NOT EXISTS DISPOSITIVO_INFORMATICA (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TIPO_DISPOSITIVO VARCHAR(255)
);

-- Inserindo dados na tabela Cliente
INSERT INTO CLIENTE (nome, cpf) VALUES ('João Silva', '123.456.789-00');
INSERT INTO CLIENTE (nome, cpf) VALUES ('Maria Oliveira', '987.654.321-00');

-- Inserindo dados na tabela InstituicaoFinanceira
INSERT INTO INSTITUICAO_FINANCEIRA (cnpj, nome) VALUES ('00.000.000/0001-00', 'Banco do Brasil');
INSERT INTO INSTITUICAO_FINANCEIRA (cnpj, nome) VALUES ('11.111.111/0001-11', 'Caixa Econômica Federal');

-- Inserindo dados na tabela Leilao sem definir o status
INSERT INTO LEILAO (DATA_INICIAL, DATA_FINAL, LOCAL, DESCRICAO, HORARIO_INICIO, HORARIO_FIM) 
VALUES ('2024-11-01', '2024-11-05', 'São Paulo, SP', 'Leilão de imóveis', '09:00:00', '17:00:00');

INSERT INTO LEILAO (DATA_INICIAL, DATA_FINAL, LOCAL, DESCRICAO, HORARIO_INICIO, HORARIO_FIM) 
VALUES ('2024-11-15', '2024-11-25', 'Rio de Janeiro, RJ', 'Leilão de veículos', '10:00:00', '19:00:00');

INSERT INTO LEILAO (DATA_INICIAL, DATA_FINAL, LOCAL, DESCRICAO, HORARIO_INICIO, HORARIO_FIM) 
VALUES ('2024-11-10', '2024-12-11', 'Limeira, SP', 'Leilão de eletrônicos', '08:00:00', '16:00:00');

-- Inserindo dados na tabela Produto com tipos específicos
INSERT INTO PRODUTO (nome, preco_inicial, DTYPE, tipo) VALUES ('Notebook Dell', 1500.00, 'DispositivoInformatica', 'Notebook');
INSERT INTO PRODUTO (nome, preco_inicial, DTYPE, tipo) VALUES ('Monitor Samsung', 800.00, 'DispositivoInformatica', 'Monitor');
INSERT INTO PRODUTO (nome, preco_inicial, DTYPE, tipo) VALUES ('Switch Cisco', 1200.00, 'DispositivoInformatica', 'Switch');
INSERT INTO PRODUTO (nome, preco_inicial, DTYPE, tipo) VALUES ('Fiat Uno', 10000.00, 'Veiculo', 'Carro');
INSERT INTO PRODUTO (nome, preco_inicial, DTYPE, tipo) VALUES ('Honda CG 150', 7000.00, 'Veiculo', 'Moto');

-- Associando produtos aos leilões
INSERT INTO LEILAO_PRODUTOS (leilao_id, produtos_id) VALUES (1, 1);
INSERT INTO LEILAO_PRODUTOS (leilao_id, produtos_id) VALUES (2, 2);
INSERT INTO LEILAO_PRODUTOS (leilao_id, produtos_id) VALUES (2, 3);

-- Associando clientes aos leilões
INSERT INTO LEILAO_CLIENTES (leilao_id, clientes_id) VALUES (1, 1);
INSERT INTO LEILAO_CLIENTES (leilao_id, clientes_id) VALUES (2, 2);

-- Associando instituições financeiras aos leilões
INSERT INTO LEILAO_INSTITUICOES_FINANCEIRAS (leilao_id, instituicoes_financeiras_id) VALUES (1, 1);
INSERT INTO LEILAO_INSTITUICOES_FINANCEIRAS (leilao_id, instituicoes_financeiras_id) VALUES (2, 2);

-- Inserindo dados na tabela Lance
INSERT INTO LANCE (cliente_id, produto_id, valor) VALUES (1, 1, 1600.00);
INSERT INTO LANCE (cliente_id, produto_id, valor) VALUES (2, 2, 850.00);